project:
  type: website

website:
  title: "Programovanie v jazyku Python"
  
  navbar:
    background: primary
    logo: pictures/python_logo.svg
    border: true
    search: true
    tools:
      - icon: envelope-at-fill
        menu:
            - text: "Ing. Jakub Šperka"
              href: https://www.svf.stuba.sk/kggi/personalne-obsadenie/osobna-stranka-ing.-jakub-sperka.html?page_id=10250
            - text: "Ing. Nikita Yakshin"
              href: https://www.svf.stuba.sk/kggi/personalne-obsadenie/osobna-stranka-ing.-nikita-yakshin.html?page_id=9627
            - text: "doc.Ing. Renata Ďuračiová, PhD."
              href: https://www.svf.stuba.sk/sk/katedry/katedra-geodetickych-zakladov/personalne-obsadenie/osobna-stranka-ing.-renata-duraciova-phd.html?page_id=3005
    left:
    - text: Domov
      href: index.qmd
    - href: toc.qmd
    - href: about.qmd
    
    
  sidebar:
    style: "docked"
    background: light
    search: false
    collapse-level: 1
    contents:
         - section: "🚀 Základy Pythonu"
           contents:
           - content/anaconda.qmd
           - content/venv.qmd
           - content/hello_world.ipynb
           - content/premenne_a_datove_typy.ipynb
           - content/operatory.ipynb
           - content/type_a_konverzia.ipynb
           - content/vstup_input.ipynb
           - content/komentovanie_kodu.ipynb
         - section: "💾 Dátové štruktúry"
           contents:
           - wip.qmd 
         - section: "🏗️ Riadiace štruktúry"
           contents:
           - content/podmienky.ipynb
           - content/cykly.ipynb
         - section: "⚙️ Funkcie"
           contents:
           - wip.qmd
         - section: "📚 Úvod do knižníc"
           contents:
           - wip.qmd
         - section: "🗂️ Spracovanie dát"
           contents: 
           - wip.qmd 
         - section: "💡 Zaujímavosti"
           contents:
           - wip.qmd
format:
  html:
    theme: superhero
    toc: true
    lang: sk
    respect-user-color-scheme: true
    code-overflow: wrap
    code-fold: show
    code-tools: false
    code-line-numbers: true
    highlight-style: github